GET http://localhost:3000/users/1
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjExLCJlbWFpbCI6ImF5c2hhMDA0QGdtYWlsLmNvbSIsImlhdCI6MTczNzAyMDA2NiwiZXhwIjoxNzM3MDIyNTY2LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.hBk5eD1hyWMKGxNIS82iddj4obbnBBQPWiGWiE247NI