POST http://localhost:3000/users
Content-Type: application/json
{
  "firstName": "musa",
  "lastName": "isa",
  "email": "musa9@gmail.com",
  "password": "@musakk9099A"
}
#  {
        
#         // "address" : "Malalin-gabas, kaduna",
#         // "isAuth": true
#       }

