POST http://localhost:3000/users
Content-Type: application/json
{
  "firstName": "Aisha",
  "lastName": "Ahmad",
  "email": "aysha004@gmail.com",
  "password": "@Ayshahmad1200"
}
#  {
        
#         // "address" : "Malalin-gabas, kaduna",
#         // "isAuth": true
#       }

